#### VERSION ####
version: '3.7'

#### SERVICES ####
services:

#### DATABASE MONGO ####
  mongo:
    image: mongo:4.0.10
    container_name: mongo
    restart: always
    volumes:
      - ./data/db:/data/db
    ports:
      - 27017:27017

#### VISUALIZER MONGO ####
  mongo-express:
    image: mongo-express:0.54
    container_name: mongo-express
    restart: always
    ports:
      - 8081:8081
    depends_on:
      - mongo
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: root
      ME_CONFIG_BASICAUTH_PASSWORD: root
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
    links:
      - mongo

#### BACKEND IN NODE ####
  backend:
    build: ./sv
    container_name: backend
    restart: always
    depends_on:
      - mongo
    environment:
       - CHOKIDAR_USEPOLLING=true
    ports:
      - 3000:3000
    volumes:
      - ./sv/src:/app/src
